version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dropick_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]      
      interval: 10s
      timeout: 5s
      retries: 5