name: Bump version and publish release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  bump_version_and_tag:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    permissions:
      contents: write
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
  build_and_release:
    runs-on: ubuntu-latest
    needs: bump_version_and_tag
    permissions:
      contents: write
    if: github.event.pull_request.merged == false
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: build executable artifact
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/dropick_api/${{ matrix.goos }}_${{ matrix.goarch }}_${{ needs.bump_version_and_tag.outputs.new_version }} ./cmd/dropick_api
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.bump_version_and_tag.outputs.new_tag }}
          name: Release ${{ needs.bump_version_and_tag.outputs.new_tag }}
          body: ${{ needs.bump_version_and_tag.outputs.changelog }}
          artifacts: |
            ./bin/dropick_api/**/*
